name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@befbc52f24215555cb601b0d824b2987c1d49d0b # v0.4.3
    secrets: inherit
