name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@d87ca69d0f0464d70cdece61c88919725a3571a2 # v0.4.4
    secrets: inherit
