name: Contributors

on:
  schedule:
    - cron: '49 4 1 * *'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  contributors:
    permissions:
      pull-requests: write
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/contributors.yml@69a76bc5d13145693ca13d24a418942b59fce727 # v0.6.3
    secrets: inherit
