name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test.yml@6ed4490472a56b1d952231565aac80f13c2d143c # v0.2.16
    secrets: inherit
