name: Monitor bot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

permissions:
  contents: read

jobs:
  monitor-pr:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    uses: go-openapi/ci-workflows/.github/workflows/monitor-bot-pr.yml@93b16765c4045dbd4dac2372803294298aa7592a # v0.3.3
    secrets: inherit
