name: Monitor bot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

permissions:
  contents: read

jobs:
  monitor-pr:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    uses: go-openapi/ci-workflows/.github/workflows/monitor-bot-pr.yml@38ed6bf083115440d79b475442d6cf99ee450180 # v0.6.1
    secrets: inherit
