name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@befbc52f24215555cb601b0d824b2987c1d49d0b # v0.4.3
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
